export const TEXR_2_IMAGE = '/Text2Image'
export const IMAGE_2_IMAGE = '/Image2Image'
export const IMAGE_2_IMAGE_WIYH_MASKST = '/Image2ImageWithMaskst'
export const INPAINTING = '/Inpainting'
export const OUTPAINTING = '/Outpainting'
export const COLLECTION = '/Collection'
